const WA='+2348054776613';
const products=[
{id:'letters-to-god',name:'Letters to God',category:'journals',price:12500,kind:'journal-pink',description:'A gentle space for prayers, reflections and honest conversations with God.'},
{id:'true-love',name:'True Love Journal',category:'journals',price:11000,kind:'journal-rose',description:'A purposeful journal for reflecting on love, values and relationships.'},
{id:'bloom',name:'Bloom',category:'journals',price:12000,kind:'journal-floral',description:'A reflective journal for growth, becoming and documenting your seasons.'},
{id:'smart-planner',name:'The Smart Planner',category:'journals',price:15000,kind:'planner',description:'A practical planner for goals, routines, priorities and intentional days.'},
{id:'faith-over-fear',name:'Faith Over Fear T-Shirt',category:'clothing',price:18000,kind:'faith-shirt',sizes:['S','M','L','XL','XXL'],description:'A comfortable faith-inspired piece carrying a simple reminder to choose faith over fear.'},
{id:'purpose-sweatshirt',name:'Purpose Sweatshirt',category:'clothing',price:28000,kind:'purpose-sweatshirt',sizes:['S','M','L','XL','XXL'],description:'A soft everyday sweatshirt designed around purpose, identity and intentional living.'}
];
function money(n){return new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN',maximumFractionDigits:0}).format(n)}
function getCart(){return JSON.parse(localStorage.getItem('pc_cart')||'[]')}
function saveCart(c){localStorage.setItem('pc_cart',JSON.stringify(c));updateCartBadge()}
function addToCart(id,qty=1){const c=getCart(),x=c.find(i=>i.id===id);if(x)x.qty+=qty;else c.push({id,qty});saveCart(c);toast('Added to your cart ♡')}
function updateQty(id,d){const c=getCart(),x=c.find(i=>i.id===id);if(!x)return;x.qty+=d;saveCart(x.qty<1?c.filter(i=>i.id!==id):c);renderCart()}
function removeFromCart(id){saveCart(getCart().filter(i=>i.id!==id));renderCart()}
function updateCartBadge(){document.querySelectorAll('.cart-count').forEach(x=>x.textContent=getCart().reduce((s,i)=>s+i.qty,0))}
function wa(message){window.open('https://wa.me/'+WA+'?text='+encodeURIComponent(message),'_blank')}
function toast(t){const x=document.querySelector('.toast');if(!x)return;x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)}
function card(p){return `<article class="product-card"><a href="product.html?id=${p.id}"><div class="product-media">${p.category==='journals'?`<div class="mock ${p.kind}">${p.name}</div>`:`<div class="shirt">${p.name.includes('Faith')?'FAITH OVER FEAR':'PURPOSE'}</div>`}</div></a><div class="product-info"><div class="eyebrow">${p.category==='journals'?'JOURNAL':'FAITH WEAR'}</div><h3>${p.name}</h3><p style="color:var(--muted)">${p.description}</p><div style="display:flex;justify-content:space-between;align-items:center;gap:10px"><strong class="price">${money(p.price)}</strong><button class="btn btn-primary" onclick="addToCart('${p.id}')">Add to Cart</button></div></div></article>`}
function renderProducts(list,root){if(root)root.innerHTML=list.map(card).join('')}
function renderShop(filter='all'){const root=document.querySelector('#shop-grid');if(!root)return;let list=filter==='all'?products:products.filter(p=>p.category===filter);renderProducts(list,root);document.querySelectorAll('.filter').forEach(b=>b.classList.toggle('active',b.dataset.filter===filter))}
function renderProduct(){const root=document.querySelector('#product-page');if(!root)return;const id=new URLSearchParams(location.search).get('id')||'letters-to-god';const p=products.find(x=>x.id===id)||products[0];root.innerHTML=`<div class="container product-detail"><div class="product-large">${p.category==='journals'?`<div class="mock" style="width:55%;height:72%;font-size:1.2rem">${p.name}</div>`:`<div class="shirt" style="width:60%;height:70%;font-size:1rem">${p.name.includes('Faith')?'FAITH OVER FEAR':'PURPOSE'}</div>`}</div><div class="product-copy"><div class="eyebrow">${p.category==='journals'?'JOURNAL':'FAITH WEAR'}</div><h2>${p.name}</h2><div class="price" style="font-size:1.3rem">${money(p.price)}</div><p>${p.description}</p>${p.sizes?`<strong>Size</strong><div class="size-row">${p.sizes.map((s,i)=>`<button class="size ${i===1?'active':''}">${s}</button>`).join('')}</div>`:''}<label class="field" style="max-width:120px">Quantity<input id="product-qty" type="number" value="1" min="1"></label><div style="display:flex;gap:10px;flex-wrap:wrap;margin-top:18px"><button class="btn btn-primary" onclick="addToCart('${p.id}',Math.max(1,+document.querySelector('#product-qty').value||1))">Add to Cart →</button><button class="btn btn-ghost" onclick="wa('Hello Pearls & Crafts! I would like to order ${p.name}. Please send me the available options, delivery and payment details.')">Order on WhatsApp</button></div><div class="story-card" style="margin-top:25px"><strong>Nationwide delivery</strong><p style="margin:4px 0 0;color:var(--muted)">Delivery across Nigeria. Exact delivery cost is confirmed with your order.</p></div></div></div>`}
function renderCart(){const root=document.querySelector('#cart-root');if(!root)return;const c=getCart();if(!c.length){root.innerHTML='<div class="story-card center"><h2>Your cart is waiting for something beautiful.</h2><p>Explore the collection and add a piece that speaks to you.</p><a class="btn btn-primary" href="shop.html">Explore the Shop →</a></div>';return}let subtotal=0;root.innerHTML=`<div class="cart-layout"><div class="contact-card"><h2>Your Cart</h2>${c.map(i=>{const p=products.find(x=>x.id===i.id);subtotal+=p.price*i.qty;return `<div class="cart-item"><div class="cart-thumb">${p.category==='journals'?p.name.split(' ')[0]:'FAITH'}</div><div><strong>${p.name}</strong><div class="price">${money(p.price)}</div></div><div class="qty"><button onclick="updateQty('${p.id}',-1)">−</button><span>${i.qty}</span><button onclick="updateQty('${p.id}',1)">+</button></div><button class="iconbtn" onclick="removeFromCart('${p.id}')">🗑</button></div>`}).join('')}<a class="btn btn-ghost" href="shop.html" style="margin-top:20px">← Continue Shopping</a></div><aside class="summary"><h3>Order Summary</h3><div class="summary-row"><span>Subtotal</span><strong>${money(subtotal)}</strong></div><div class="summary-row"><span>Delivery</span><span>Confirmed at checkout</span></div><div class="summary-row summary-total"><span>Total before delivery</span><strong>${money(subtotal)}</strong></div><a class="btn btn-primary" href="checkout.html" style="width:100%;margin-top:15px">Proceed to Checkout →</a><button class="btn btn-ghost" style="width:100%;margin-top:10px" onclick="wa('Hello Pearls & Crafts! I would like to place an order for: ${c.map(i=>{const p=products.find(x=>x.id===i.id);return `${p.name} x${i.qty}`}).join(', ')}. Please assist me with delivery and payment.')">Order via WhatsApp</button></aside></div>`}
function initCheckout(){const form=document.querySelector('#checkout-form');if(!form)return;const c=getCart();const total=c.reduce((s,i)=>s+products.find(p=>p.id===i.id).price*i.qty,0);document.querySelector('#checkout-total').textContent=money(total);form.addEventListener('submit',e=>{e.preventDefault();const d=new FormData(form);const items=c.map(i=>{const p=products.find(x=>x.id===i.id);return `${p.name} x${i.qty}`}).join(', ');wa(`Hello Pearls & Crafts! I would like to place an order.\n\nName: ${d.get('name')}\nPhone: ${d.get('phone')}\nEmail: ${d.get('email')}\nDelivery address: ${d.get('address')}\nState: ${d.get('state')}\nCity: ${d.get('city')}\nItems: ${items}\nTotal before delivery: ${money(total)}\n\nPlease confirm my order.`);localStorage.removeItem('pc_cart');setTimeout(()=>location.href='thank-you.html',400)})}
function initContact(){const f=document.querySelector('#contact-form');if(!f)return;f.addEventListener('submit',e=>{e.preventDefault();const d=new FormData(f);wa(`Hello Pearls & Crafts!\n\nName: ${d.get('name')}\nPhone: ${d.get('phone')}\nEmail: ${d.get('email')}\nSubject: ${d.get('subject')}\nMessage: ${d.get('message')}`)})}
function init(){updateCartBadge();renderProduct();renderCart();initCheckout();initContact();document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>renderShop(b.dataset.filter)));const f=new URLSearchParams(location.search).get('filter');if(document.querySelector('#shop-grid'))renderShop(f||'all')}
// Use event delegation so the dynamically loaded header controls always work.
document.addEventListener('click',e=>{const waButton=e.target.closest('[data-wa]');if(waButton){wa(waButton.dataset.wa);return}const menuButton=e.target.closest('.mobile-toggle');if(menuButton){document.querySelector('.navlinks')?.classList.toggle('open')}});
document.addEventListener('DOMContentLoaded',init);